server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/hmdp?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123


  data:
    redis:
      port: 6379
      host: 192.168.102.128
      password: 123123
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 1
          time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段

mybatis-plus:
  type-aliases-package: wallswq.dianping.domain

logging:
  level:
    wallswq.dianping: debug
